name: kafka-user-operator
rbacEnable: true

namespace: dev
imagePullSecretName: "" # your image pull secret

topicOperator:
  - name: dev-msk
    namespace: dev
    image: quay.io/babylonhealth/kafka-operator
    tag: 0.16.1
    auth: tls
    kafka_bootstrap_servers:
    - b-3.msk-kafka-dev-uk.xxxxxx.c4.kafka.eu-west-2.amazonaws.com:9094
    - b-1.msk-kafka-dev-uk.xxxxxx.c4.kafka.eu-west-2.amazonaws.com:9094
    - b-2.msk-kafka-dev-uk.xxxxxx.c4.kafka.eu-west-2.amazonaws.com:9094
    resources:
      requests:
        cpu: "1000m"
        memory: "1000Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    env:
      SENTRY_DSN: "none"
      STRIMZI_RESOURCE_LABELS: "strimzi.io/cluster=dev-msk" # ensure this value is is the same as the name variable above
      STRIMZI_KAFKA_BOOTSTRAP_SERVERS: "127.0.0.1:32401,127.0.0.1:32402,127.0.0.1:32403" # This should match the number of Kafka Brokers
      STRIMZI_ZOOKEEPER_CONNECT: "" # Connection String for your ZK nodes
      STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS: "20000"
      STRIMZI_FULL_RECONCILIATION_INTERVAL_MS: "900000"
      STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS: "6"
      STRIMZI_LOG_LEVEL: INFO
      STRIMZI_NAMESPACE: dev
      STRIMZI_TLS_ENABLED: "false"
