{{- if .Values.userOperator -}}
{{- range $operator := .Values.userOperator }}

apiVersion: babylontech.co.uk/v1alpha1
kind: Secret
metadata:
  name: {{ $.Values.name }}-user-secrets-{{ $operator.name }}
  namespace: {{ $operator.namespace }}
  labels:
    app: {{ $.Values.name }}-{{ $operator.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Values.name }}
spec:
  template:
    secretType: Opaque
    metadata:
      name: {{ $.Values.name }}-user-secrets-{{ $operator.name }}
      annotations:
        controller: secret-manager
  backendName: vault-default
  backendType: vault
  refreshPeriod: 300
  vault:
    storageType: kv1
    secrets:
      - path: {{ $operator.secrets.kakfa_ca_crt }}
        backendKey: value
        base64encoded: false
        secretKey: ca.crt
      - path: {{ $operator.secrets.kakfa_ca_key }}
        backendKey: value
        base64encoded: false
        secretKey: ca.key
---
{{- end}}
{{- end}}
