{{- if .Values.userOperator -}}
{{- range $operator := .Values.userOperator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-user-operator-{{ $operator.name }}
  namespace: {{ $operator.namespace }}
  labels:
    app: {{ $.Values.name }}-{{ $operator.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Values.name }}
automountServiceAccountToken: true
---
{{- end }}
{{- end }}
