{{- if .Values.topicOperator }}
{{- range $operator := .Values.topicOperator }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-topic-operator-role-{{ $operator.name }}
  namespace: {{ $operator.namespace }}
  labels:
    app: {{ $.Values.name }}-{{ $operator.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Values.name }}
rules:
  - apiGroups:
    - kafka.strimzi.io
    resources:
    - kafkatopics
    - kafkatopics/status
    verbs:
    - get
    - watch
    - list
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-topic-operator-binding-{{ $operator.name }}
  namespace: {{ $operator.namespace }}
  labels:
    app: {{ $.Values.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Values.name }}
subjects:
- kind: ServiceAccount
  name: kafka-topic-operator-{{ $operator.name }}
roleRef:
  kind: Role
  name: kafka-topic-operator-role-{{ $operator.name }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end}}
{{- end}}
